### PR TITLE
[MapleLib] Fixed copyright header parsing (#77)

### LINKED ISSUE #77: Unable to open certain files
Came across this issue quite randomly while editing my UI and Map files (GMS v84).
I somehow managed to break my UI and Map files to the point that the current MapleLib is unable to open the files, however ancient versions of MapleLib are able to open it fine under "MSEA (old)" encryption.
Seems to happen also if the file only has a single image inside it.

Harepacker-resurrected:
image

Ancient version of the original HaRepacker:
image

Resurrected still seems to open and edit the rest of my files perfectly fine (under "GMS (old)" encryption) -- not sure what went wrong!

Sample of the WZ file that Harepacker-resurrected is unable to parse:
[UI_Test.zip](https://github.com/lastbattle/Harepacker-resurrected/files/5433176/UI_Test.zip)

The exception seems to be thrown by this line of code: https://github.com/lastbattle/Harepacker-resurrected/blob/6093ec6b8487c6ecb86eead7254c7b0e3bcf224a/MapleLib/WzLib/WzFile.cs#L216

Also.. the MapleStory client is still able to parse the file correctly.

### PR DESCRIPTION
**Pull request by shavitush**
Closes #77.

This patch fixes parsing for the copyright part in the WZ file's header and therefore, fixes parsing for WZ files that were produced by the ancient versions of HaCreator. I found that the issue happens because the game client reads a fixed amount of bytes for the copyright string however the old version of MapleLib for some reason wrote a 50 instead of a 0 (null terminator) at the end of the string, therefore -- breaking it all apart

It's a bit hacky (and hardcoded). I accomplished it by reversing the parsing from the MapleLib library I had which happened to have the correct parsing patched into it. 

I have tested this patch on various WZ files including stock v83, a variety of modded v83s, stock v84, v92, v95, v127, v162, v176, stock v179, Kastia's v179, v213.. all seems well!

### CODE REVIEW

File: MapleLib/WzLib/WzFile.cs [hunk 1]
```diff
@@ -206,14 +206,14 @@ internal bool ParseMainWzDirectory(out string parseErrorMessage, bool lazyParse
...
-            };
-            reader.ReadBytes((int)(Header.FStart - reader.BaseStream.Position));
+            this.Header = new WzHeader();
+            this.Header.Ident = reader.ReadString(4);
+            this.Header.FSize = reader.ReadUInt64();
+            this.Header.FStart = reader.ReadUInt32();
+            this.Header.Copyright = reader.ReadString((int)(Header.FStart - 17U));
+
+            reader.ReadBytes(1);
+            reader.ReadBytes((int)(Header.FStart - (ulong)reader.BaseStream.Position));
```
Comment (Arnuh) [inline MapleLib/WzLib/WzFile.cs:216]: From what I see the proper way would be just to not do these 2 byte reads and instead move the `reader.BaseStream.Position` to `Header.FStart`

Comment (shavitush) [reply MapleLib/WzLib/WzFile.cs:216]: as much as I'd like to do that, that would break the header upon saving the file

**Comment by lastbattle** [comment]
Looks ok in my testing on GMS v83, v64, v188.
